// <auto-generated />
namespace WebAPI.Migrations.AccountManagement
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updte_User_ColumnType_DateOfBirth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updte_User_ColumnType_DateOfBirth));
        
        string IMigrationMetadata.Id
        {
            get { return "201811260937167_Updte_User_ColumnType_DateOfBirth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
